import time
from selenium.webdriver import ActionChains
from threading import Thread
from selenium.webdriver.common.by import By
from selenium import webdriver
import json

with open("data_user.json", "r") as file:
    Users = json.load(file)


driver = webdriver.Firefox()
driver.get("http://bluedartstorageuat.z29.web.core.windows.net/auth/signin")
time.sleep(4)
driver.maximize_window()
driver.find_element(By.CLASS_NAME,'form-control').send_keys("subadminuat@gmail.com")
print("email id passed")
driver.find_element(By.CLASS_NAME,'ng-pristine').send_keys("password")
print("password passed")
button=driver.find_element(By.XPATH,"//button[text()='Sign In']")
button.click()
time.sleep(3)
print("login passed")
driver.maximize_window()
time.sleep(3)
button1=driver.find_element(By.XPATH,"//span[text()='Users']")
button1.click()
time.sleep(5)
for user in Users:
    try:
        button3=driver.find_element(By.XPATH,"/html[1]/body[1]/app-root[1]/app-admin[1]/div[1]/div[1]/app-esa-user[1]/div[1]/div[1]/button[1]/span[1]")
        button3.click()
        driver.find_element(By.XPATH,("//input[@formcontrolname='esa_id']")).send_keys(user["esa_id"])
        time.sleep(1)
        driver.find_element(By.XPATH,("//input[@formcontrolname='password']")).send_keys(user["password"])
        time.sleep(1)
        driver.find_element(By.XPATH,("//input[@formcontrolname='first_name']")).send_keys(user["first_name"])
        time.sleep(1)
        driver.find_element(By.XPATH,("//input[@formcontrolname='last_name']")).send_keys(user["last_name"])
        time.sleep(1)
        driver.find_element(By.XPATH,("//input[@formcontrolname='contact_number']")).send_keys(user["contact_number"])
        time.sleep(1)
        driver.find_element(By.XPATH,("//input[@formcontrolname='email_id']")).send_keys(user["email_id"])
        time.sleep(1)
        driver.find_element(By.XPATH,("//input[@formcontrolname='address_1']")).send_keys(user["address_1"])
        time.sleep(1)
        driver.find_element(By.XPATH,("//input[@formcontrolname='address_2']")).send_keys(user["address_2"])
        time.sleep(1)
        driver.find_element(By.XPATH,("//input[@formcontrolname='address_3']")).send_keys(user["address_3"])
        time.sleep(1)
        driver.find_element(By.XPATH,("//input[@formcontrolname='city']")).send_keys(user["city"])
        time.sleep(1)
        driver.find_element(By.XPATH,("//input[@formcontrolname='state']")).send_keys(user["state"])
        time.sleep(1)
        driver.find_element(By.XPATH,("//input[@formcontrolname='country']")).send_keys(user["country"])
        time.sleep(1)
        driver.find_element(By.XPATH,("//input[@formcontrolname='country_code']")).send_keys(user["country_code"])
        time.sleep(1)
        driver.find_element(By.XPATH,("//input[@formcontrolname='postal_code']")).send_keys(user["postal_code"])
        time.sleep(1)
        driver.find_element(By.XPATH,("//input[@formcontrolname='aadhaar_number']")).send_keys(user["aadhaar_number"])
        time.sleep(1)
        driver.find_element(By.XPATH,("//input[@formcontrolname='license_key']")).send_keys(user["license_key"])
        time.sleep(1)
        driver.find_element(By.XPATH,("//input[@formcontrolname='area_code']")).send_keys(user["area_code"])
        time.sleep(1)
        driver.find_element(By.XPATH,("//input[@formcontrolname='login_id']")).send_keys(user["login_id"])
        time.sleep(1)
        driver.find_element(By.XPATH,("//input[@formcontrolname='pu_code']")).send_keys(user["pu_code"])
        time.sleep(1)
        driver.find_element(By.XPATH,("//input[@formcontrolname='pu_name']")).send_keys(user["pu_name"])
        time.sleep(1)
        driver.find_element(By.XPATH,("//input[@formcontrolname='emp_name']")).send_keys(user["emp_name"])
        time.sleep(1)
        driver.find_element(By.XPATH,("//input[@formcontrolname='emp_code']")).send_keys(user["emp_code"])
        time.sleep(1)
        driver.find_element(By.XPATH, "//*[@id='mat-select-value-5']/span").click()
        time.sleep(5)
        driver.find_element(By.XPATH, f"//span[normalize-space()='{user['services']}']").click()
        time.sleep(3)
        #driver.find_element(By.XPATH,"//*[@id='mat-option-6']/span").click()
        #time.sleep(1)
       # driver.find_element(By.XPATH,"//*[@id='mat-option-7']/span").click()
        #time.sleep(1)
        element2=driver.find_element(By.XPATH,"(//h2[normalize-space()='Add ESA User'])[1]")
        time.sleep(1)
        actions = ActionChains(driver)
        actions.move_to_element(element2).click().perform()
        time.sleep(3)
        driver.find_element(By.XPATH,"(//span[normalize-space()='Add'])[1]").click()
        time.sleep(5)
        Usercreation_validation1=driver.find_element(By.XPATH,"//h2[normalize-space()='Added User Successfully.']")
        if Usercreation_validation1.is_displayed():
            print(" add user created sucessfull ")
        else:
            print("add user creation  failed")
        time.sleep(3)
        driver.find_element(By.XPATH,"//*[@id='added-user-confirm']").click()
        time.sleep(2)
        button4=driver.find_element(By.XPATH,"/html[1]/body[1]/app-root[1]/app-admin[1]/div[1]/div[1]/app-esa-user[1]/div[1]/button[1]/span[1]")
        button4.click()
        time.sleep(5)
        file_input=driver.find_element(By.XPATH,"//*[@id='file']")
        file_input.send_keys("C:\\Users\\eshipz\\Downloads\\esa_template (10).csv")
        time.sleep(3)
        driver.find_element(By.XPATH,"//*[@id='exampleModal']/div/div/div[3]/button[2]").click()
        time.sleep(3)
        Usercreation_validation=driver.find_element(By.XPATH,"//h2[normalize-space()='Uploaded Successfully.']")
        if Usercreation_validation.is_displayed():
            print("user created sucessfull ")
        else:
            print("user creation  failed")
        time.sleep(3)
    except Exception as error:
        print(f"Error: {error}")

    driver.quit()


