import time
from selenium.webdriver import ActionChains
from threading import Thread
from selenium.webdriver.common.by import By
from selenium import webdriver
import json

with open("data_credit.json", "r") as file:
  customers = json.load(file)
driver = webdriver.Firefox()
driver.get("http://bluedartstorageuat.z29.web.core.windows.net/auth/signin")
time.sleep(4)
driver.maximize_window()
driver.find_element(By.CLASS_NAME,'form-control').send_keys("channelsmart@eshipz.com")
driver.find_element(By.CLASS_NAME,'ng-pristine').send_keys("password")
button=driver.find_element(By.XPATH,"//button[text()='Sign In']")
button.click()
time.sleep(3)
print("login passed")
driver.maximize_window()
time.sleep(3)
button1=driver.find_element(By.XPATH,"//span[text()='Customers']")
button1.click()
time.sleep(1)
for customer in customers:
    try:
         button2 = driver.find_element(By.XPATH,"/html[1]/body[1]/app-root[1]/app-admin[1]/div[1]/div[1]/app-esa-customers[1]/div[1]/div[1]/button[1]/span[1]")
         button2.click()
         time.sleep(2)
         driver.find_element(By.XPATH,("//input[@formcontrolname='pancard_number']")).send_keys(customer["pancard_number"])
         time.sleep(2)
         driver.find_element(By.XPATH,("//input[@formcontrolname='aadhaar_number']")).send_keys(customer["aadhaar_number"])
         time.sleep(2)
         driver.find_element(By.XPATH,("//input[@formcontrolname='customer_code']")).send_keys(customer["customer_code"])
         time.sleep(2)
         driver.find_element(By.XPATH,"//*[@id='mat-select-value-5']/span").click()
         time.sleep(2)
         driver.find_element(By.XPATH, f"//span[normalize-space()='{customer['services']}']").click()
         time.sleep(1)
         element3=driver.find_element(By.XPATH,"(//h2[normalize-space()='Add Customer'])[1]")
         time.sleep(1)
         actions = ActionChains(driver)
         actions.move_to_element(element3).click().perform()
         time.sleep(1)
         driver.find_element(By.XPATH,("//input[@formcontrolname='username']")).send_keys(customer["username"])
         time.sleep(2)
         driver.find_element(By.XPATH,("//input[@formcontrolname='addressline1']")).send_keys(customer["addressline1"])
         time.sleep(2)
         driver.find_element(By.XPATH,("//input[@formcontrolname='addressline2']")).send_keys(customer["addressline2"])
         time.sleep(2)
         driver.find_element(By.XPATH,("//input[@formcontrolname='addressline3']")).send_keys(customer["addressline3"])
         time.sleep(2)
         driver.find_element(By.XPATH,("//input[@formcontrolname='company_name']")).send_keys(customer["company_name"])
         time.sleep(2)
         driver.find_element(By.XPATH,("//input[@formcontrolname='city']")).send_keys(customer["city"])
         time.sleep(2)
         driver.find_element(By.XPATH,("//input[@formcontrolname='pincode']")).send_keys(customer["pincode"])
         time.sleep(2)
         driver.find_element(By.XPATH,("//input[@formcontrolname='state']")).send_keys(customer["state"])
         time.sleep(2)
         driver.find_element(By.XPATH,("//input[@formcontrolname='phone_number']")).send_keys(customer["phone_number"])
         time.sleep(2)
         driver.find_element(By.XPATH,("//input[@formcontrolname='email']")).send_keys(customer["email"])
         time.sleep(2)
         driver.find_element(By.XPATH,"//*[@id='mat-checkbox-1']/label/span[1]").click()
         time.sleep(2)
         driver.find_element(By.XPATH,"//*[@id='mat-dialog-0']/app-customer-dialog-modal/mat-dialog-actions/button[2]/span[1]").click()
         time.sleep(2)
         print("manual customer creation sucessfull ")
         Creditscustomer_validation1=driver.find_element(By.XPATH,"//h2[normalize-space()='Added Customer Successfully.']")
         if Creditscustomer_validation1.is_displayed():
            print(" ADD customer created sucessfull ")
         else:
              print("customer creation  failed")
         time.sleep(3)
         confirm_button = driver.find_element(By.ID, "added-customer-confirm")
         confirm_button.click()
         time.sleep(3)
         button3=driver.find_element(By.XPATH,"/html[1]/body[1]/app-root[1]/app-admin[1]/div[1]/div[1]/app-esa-customers[1]/div[1]/div[1]/button[2]/span[1]")
         button3.click()
         time.sleep(2)
         file_input=driver.find_element(By.XPATH,"//*[@id='file']")
         file_input.send_keys("C:\\Users\\eshipz\\Downloads\\customer_template (9).csv")
         time.sleep(3)
         driver.find_element(By.XPATH,"//*[@id='exampleModal']/div/div/div[3]/button[2]").click()
         time.sleep(2)
         Creditscustomer_validation=driver.find_element(By.XPATH,"//h2[normalize-space()='Customers Created Successfully.']")
         if Creditscustomer_validation.is_displayed():
                print("customer created sucessfull ")
         else:
                print("customer creation  failed")
         time.sleep(3)
    except Exception as error:
        print(f"Error: {error}")
driver.quit()
