name: eShipz Playwright Test Suite

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Select Environment
        required: true
        default: uat
        type: choice
        options:
          - uat
          - prod

jobs:
  tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: eshipz_framework

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ../requirements.txt
          python -m playwright install --with-deps

      - name: Run Order Sanity Test
        run: pytest tests/test_order_sanity.py -s --reruns 2 || true
        env:
          BASE_URL: ${{ github.event.inputs.environment == 'prod' && 'https://app.eshipz.com' || 'https://uat.eshipz.com:444' }}
          CI: true
          PLAYWRIGHT_HEADLESS: true

      - name: Run Order Shipment Creation
        run: pytest tests/test_order_shipment_creation.py -s --reruns 2 || true
        env:
          BASE_URL: ${{ github.event.inputs.environment == 'prod' && 'https://app.eshipz.com' || 'https://uat.eshipz.com:444' }}
          CI: true
          PLAYWRIGHT_HEADLESS: true

      - name: Run Sanity Shipment Flow
        run: pytest tests/test_sanity_shipment_flow_v2.py -s --reruns 2 || true
        env:
          BASE_URL: ${{ github.event.inputs.environment == 'prod' && 'https://app.eshipz.com' || 'https://uat.eshipz.com:444' }}
          CI: true
          PLAYWRIGHT_HEADLESS: true

      - name: Run All Shipments Test
        run: pytest tests/test_all_shipments_v2.py -s --reruns 2 || true
        env:
          BASE_URL: ${{ github.event.inputs.environment == 'prod' && 'https://app.eshipz.com' || 'https://uat.eshipz.com:444' }}
          CI: true
          PLAYWRIGHT_HEADLESS: true

      - name: Run Reverse Sanity Flow
        run: pytest tests/test_reverse_sanity.py -s --reruns 2 || true
        env:
          BASE_URL: ${{ github.event.inputs.environment == 'prod' && 'https://app.eshipz.com' || 'https://uat.eshipz.com:444' }}
          CI: true
          PLAYWRIGHT_HEADLESS: true


      - name: Upload Playwright Videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-videos
          path: eshipz_framework/videos